// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7keKbNEYc1juf1eWl3jIOR3asacCXsnQ',
    appId: '1:279708646624:android:4a4e12061abca92e94e485',
    messagingSenderId: '279708646624',
    projectId: 'swim-app-moby',
    storageBucket: 'swim-app-moby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqY4VqCKWIDHo-SqRmoxaa-a3YKx9NeTY',
    appId: '1:279708646624:ios:a5501c588be91f3794e485',
    messagingSenderId: '279708646624',
    projectId: 'swim-app-moby',
    storageBucket: 'swim-app-moby.firebasestorage.app',
    iosBundleId: 'com.ti4gan.swimapp.moby',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACx00P3R_Dbmegbqpj12WARHIM2cmu8WM',
    appId: '1:279708646624:web:00ba7e58f12149e094e485',
    messagingSenderId: '279708646624',
    projectId: 'swim-app-moby',
    authDomain: 'swim-app-moby.firebaseapp.com',
    storageBucket: 'swim-app-moby.firebasestorage.app',
    measurementId: 'G-KSD60NKYND',
  );

}