// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZsLZTwTxSeQcxKu6EBeOfy5Z70KKKVs',
    appId: '1:120164374295:android:4cb1bfaca45cb979cc0952',
    messagingSenderId: '120164374295',
    projectId: 'moby-9b804',
    databaseURL: 'https://moby-9b804-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moby-9b804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rBCm0yWznejnaCu7PLpcjcV3_14DnEE',
    appId: '1:120164374295:ios:1b7006d72e1794dbcc0952',
    messagingSenderId: '120164374295',
    projectId: 'moby-9b804',
    databaseURL: 'https://moby-9b804-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moby-9b804.firebasestorage.app',
    iosClientId: '120164374295-6hgh2im37l61osijltsbimhumfsc473h.apps.googleusercontent.com',
    iosBundleId: 'com.example.swimApp',
  );

}